import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowDownUp, ArrowRight, ChevronDown, CircleUserRound, Gamepad2, Menu, Search, ShieldCheck, ShoppingBag, Sparkles, X } from 'lucide-react';
import { isConfigured, supabase } from './lib/supabase';
import { MAX_RENTAL_HOURS, rentalQuote } from './lib/rental-rules';

const money = (value) => value == null ? '—' : `RM${Number(value).toFixed(2)}`;
const sellerTelegram = (message) => `https://t.me/Artz_v2?text=${encodeURIComponent(message)}`;

function gameSlugBase(name) {
  const normalized = String(name || '').trim().toLowerCase();
  const compact = normalized.replace(/[^a-z0-9]/g, '');
  if (compact === 'pubg') return 'Pubg';
  if (compact === 'efootball' || compact === 'pes') return 'Pes';
  return normalized.split(/[^a-z0-9]+/).filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join('_');
}

function nextGameSlug(name, games = []) {
  const base = gameSlugBase(name);
  if (!base) return '';
  const prefix = `${base}_`;
  const largest = games.reduce((max, item) => {
    if (!item.slug?.startsWith(prefix)) return max;
    const number = Number(item.slug.slice(prefix.length));
    return Number.isInteger(number) && number > max ? number : max;
  }, 0);
  return `${prefix}${largest + 1}`;
}

function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [session,setSession]=useState(null);
  useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
  return <header className="header"><div className="shell nav-wrap">
    <Link to="/" className="brand" aria-label="Artzzy Store home"><span className="brand-mark"><Gamepad2 size={20}/></span><span>ARTZZY<span className="brand-light"> STORE</span></span></Link>
    <button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X/> : <Menu/>}</button>
    <nav className={menuOpen ? 'nav-links open' : 'nav-links'}>
      <NavLink to="/games">Games</NavLink><NavLink to="/accounts">Browse accounts</NavLink><NavLink to="/orders">My orders</NavLink><NavLink to="/rentals">My rentals</NavLink>
      {session?<><NavLink to="/profile">My profile</NavLink><button className="account-link" onClick={async()=>{await supabase.auth.signOut();setSession(null);}}><CircleUserRound size={17}/> Sign out</button></>:<Link to="/login" className="account-link"><CircleUserRound size={17}/> Sign in</Link>}
    </nav>
  </div></header>;
}

function StatusStrip() {
  return <div className="status-strip"><span className="status-dot"/> Independent marketplace <span className="status-sep">/</span> Seller-arranged checkout <span className="status-sep">/</span> Contact before access</div>;
}

function ConfigNotice() {
  if (isConfigured) return null;
  return <div className="config-note"><span className="note-icon"><ShieldCheck size={16}/></span><div><strong>Store setup in progress</strong><span>Connect a new Supabase project to load games and inventory. No demo accounts are shown.</span></div><a href="#setup">Setup guide <ArrowRight size={14}/></a></div>;
}

function Home() {
  return <><main>
    <section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> YOUR NEXT LEVEL STARTS HERE</div>
      <h1>Find your next<br/><span>game-changing</span><br/>account.</h1>
      <p className="hero-desc">Buy outright or rent for the grind. Pick your game, find your fit, and get straight into the action.</p>
      <div className="hero-actions"><Link className="button button-primary" to="/accounts">Browse accounts <ArrowRight size={17}/></Link><Link className="button button-secondary" to="/games">Explore games</Link></div>
      <div className="hero-meta"><div className="avatar-stack"><span>V</span><span>E</span><span>F</span></div><div><b>Built for players</b><small>A better way to play more.</small></div><div className="meta-divider"/><div className="trust-mark"><ShieldCheck size={18}/><span>Secure<br/>checkout</span></div></div>
    </div><div className="hero-art" aria-label="Abstract neon gaming portal illustration"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-core"><span className="core-cross">✦</span><span className="core-ring"/><span className="core-word">PLAY<br/>MORE</span></div><div className="float-chip chip-top"><Sparkles size={14}/> YOUR NEXT MAIN</div><div className="float-chip chip-bottom"><span className="live-dot"/> LEVEL UP YOUR LOADOUT</div><div className="art-corner"/></div>
      <div className="hero-index"><span>01</span><i/> DISCOVER YOUR EDGE</div>
    </section>
    <ConfigNotice/>
    <section className="shell section games-section"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> PICK YOUR PLAYGROUND</div><h2>Games to get into.</h2></div><Link to="/games" className="text-link">All games <ArrowRight size={16}/></Link></div>
      <GameList compact/>
    </section>
    <section className="feature-band"><div className="shell feature-inner"><div className="feature-badge"><ShieldCheck size={22}/></div><div><span className="eyebrow">BUILT AROUND YOUR PEACE OF MIND</span><h3>Your account. Your call.</h3><p>Browse listings, then contact the seller to arrange a purchase or rental. Rental time begins only after approval.</p></div><Link to="/accounts" className="button button-secondary">Find your account <ArrowRight size={16}/></Link></div></section>
  </main><SetupFooter/></>;
}

function GameList({ compact = false }) {
  const [games, setGames] = useState([]); const [loading, setLoading] = useState(isConfigured);
  useEffect(() => { if (!supabase) return; let alive = true; supabase.from('games').select('id,name,slug,description,cover_image_url').eq('is_active', true).order('sort_order').order('name').then(({data}) => { if (alive) { setGames(data || []); setLoading(false); } }); return () => { alive = false; }; }, []);
  if (loading) return <div className="empty-panel loading-line">Loading games…</div>;
  if (!isConfigured || games.length === 0) return <div className="empty-panel"><div className="empty-icon"><Gamepad2/></div><div><strong>{isConfigured ? 'The game list is ready for your first entry.' : 'Your games will show up here.'}</strong><p>Add games from the admin dashboard once the new database is connected.</p></div>{!compact && <Link to="/login" className="text-link">Admin sign in <ArrowRight size={15}/></Link>}</div>;
  return <div className={compact ? 'game-grid compact-grid' : 'game-grid'}>{games.map((game, i) => <Link to={`/accounts?game=${game.slug}`} className={`game-card game-tone-${i % 4}`} key={game.id}>
    {game.cover_image_url && <img src={game.cover_image_url} alt=""/>}<div className="game-card-overlay"/><div className="game-number">0{i+1}</div><div className="game-card-label"><span>{game.description || 'GAME ACCOUNTS'}</span><strong>{game.name}</strong><ArrowRight size={17}/></div>
  </Link>)}</div>;
}

function Accounts() {
  const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(''); const [game, setGame] = useState(params.get('game') || ''); const [filter, setFilter] = useState('all'); const [sort, setSort] = useState('newest'); const [games, setGames] = useState([]); const [items, setItems] = useState([]); const [loading, setLoading] = useState(isConfigured);
  useEffect(() => { if (!supabase) return; supabase.from('games').select('id,name,slug').eq('is_active', true).order('name').then(({data}) => setGames(data || [])); }, []);
  useEffect(() => { if (!supabase) return; let alive = true; setLoading(true); let req = supabase.from('public_account_catalog').select('*'); if (game) req = req.eq('game_slug', game); if (filter === 'buy') req = req.gt('buy_price', 0); if (filter === 'rent') req = req.gt('rent_price', 0); if (query.trim()) req = req.ilike('search_text', `%${query.trim()}%`); req = sort === 'price' ? req.order('buy_price', {nullsFirst:false}).order('created_at', {ascending:false}) : req.order('created_at', {ascending:false}); req.then(({data}) => { if (alive) { setItems(data || []); setLoading(false); } }); return () => { alive = false; }; }, [game, filter, query, sort]);
  const setGameFilter = (v) => { setGame(v); setParams(v ? {game:v} : {}); };
  const selectedGame = games.find((item) => item.slug === game);
  return <main className="shell page-main"><div className="page-eyebrow">MARKETPLACE <span>/</span> ACCOUNTS</div><div className="page-title-row"><div><h1>Find your <span>next main.</span></h1><p>Good accounts. Clear prices. Ready when you are.</p></div><div className="results-count">{items.length} <span>LISTED</span></div></div>
    {games.length > 0 && <div className="accounts-game-list" aria-label="Browse accounts by game"><button type="button" className={!game ? 'selected' : ''} aria-pressed={!game} onClick={() => setGameFilter('')}>All games</button>{games.map((item) => <button type="button" className={game === item.slug ? 'selected' : ''} aria-pressed={game === item.slug} onClick={() => setGameFilter(item.slug)} key={item.id}>{item.name}</button>)}</div>}
    <div className="filter-bar"><label className="search-input"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search accounts or games"/></label><select value={game} onChange={e=>setGameFilter(e.target.value)}><option value="">All games</option>{games.map(g=><option value={g.slug} key={g.id}>{g.name}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Buy & rent</option><option value="buy">Buy only</option><option value="rent">Rent only</option></select><button className="sort-control" onClick={()=>setSort(sort==='newest'?'price':'newest')}><ArrowDownUp size={15}/>{sort==='newest'?'Newest':'Price'}</button></div>
    {!isConfigured ? <SetupEmpty/> : loading ? <div className="empty-panel">Searching the collection…</div> : items.length === 0 ? <div className="empty-panel large-empty"><div className="empty-icon"><ShoppingBag/></div><div><strong>{selectedGame ? `No ${selectedGame.name} accounts listed yet.` : 'No accounts found yet.'}</strong><p>{selectedGame ? 'The game is available, but it needs an account listing. In Admin, open Accounts, choose this game, add the account details and prices, then save it as Available.' : 'We’ll list fresh stock here as soon as the shop is ready. Try another search or check back soon.'}</p></div></div> : <div className="account-grid">{items.map(item=><AccountCard key={item.id} account={item}/>)}</div>}
  </main>;
}

function AccountCard({account}) { return <article className="account-card"><Link to={`/accounts/${account.id}`} className="account-image">{account.cover_image_url ? <img src={account.cover_image_url} alt=""/> : <div className="image-placeholder"><Gamepad2 size={32}/></div>}<span className="available-tag"><i/> AVAILABLE</span></Link><div className="account-info"><span className="game-name">{account.game_name}</span><Link to={`/accounts/${account.id}`} className="account-title">{account.title}</Link><div className="price-row"><div><small>BUY</small><b>{money(account.buy_price)}</b></div><div><small>RENT / HOUR</small><b>{account.rent_price > 0 ? money(account.rent_price) : 'Unavailable'}</b></div></div><Link to={`/accounts/${account.id}`} className="view-link">View account <ArrowRight size={15}/></Link></div></article>; }

function AccountDetail() {
  const id = window.location.pathname.split('/').at(-1); const [item,setItem] = useState(null);
  useEffect(() => { if(!supabase) return; supabase.from('public_account_catalog').select('*').eq('id',id).maybeSingle().then(({data})=>setItem(data)); },[id]);
  if (!isConfigured) return <main className="shell page-main"><div className="empty-panel large-empty"><div><strong>Account details unlock when the new store is connected.</strong><p>This site starts with a separate, empty inventory.</p></div><SetupLink/></div></main>;
  if (!item) return <main className="shell page-main"><div className="empty-panel large-empty"><div><strong>Account not found or unavailable.</strong><p>Try browsing the current listings.</p></div><Link className="text-link" to="/accounts">Browse accounts <ArrowRight size={15}/></Link></div></main>;
  const purchaseMessage = `Hi @Artz_v2, I want to buy ${item.game_name} account "${item.title}" (listing ${item.id}).`;
  return <main className="shell page-main"><div className="page-eyebrow"><Link to="/accounts">ACCOUNTS</Link> <span>/</span> {item.game_name?.toUpperCase()}</div><div className="detail-layout"><div className="detail-image">{item.cover_image_url?<img src={item.cover_image_url} alt="Account artwork"/>:<div className="image-placeholder"><Gamepad2 size={48}/></div>}<span className="available-tag"><i/> AVAILABLE</span></div><div className="detail-copy"><span className="game-name">{item.game_name}</span><h1>{item.title}</h1><p>{item.description || 'Account details will be available here.'}</p><div className="detail-features">{(item.features||[]).map(f=><span key={f}>{f}</span>)}</div><div className="detail-prices"><div><small>BUY THIS ACCOUNT</small><b>{money(item.buy_price)}</b><button disabled={!item.buy_price} onClick={()=>window.open(sellerTelegram(purchaseMessage),'_blank','noopener,noreferrer')}>Contact to buy <ArrowRight size={15}/></button></div><div><small>RENT THIS ACCOUNT · PER HOUR</small><b>{item.rent_price>0?money(item.rent_price):'Unavailable'}</b><button className="outline-action" disabled={!(item.rent_price>0)} onClick={()=>location.href=`/rent?account=${item.id}`}>Request rental <ChevronDown size={15}/></button></div></div><p className="private-note"><ShieldCheck size={16}/> No game login details are stored on this website. Contact the seller to arrange access.</p></div></div></main>;
}

function Checkout(){
  const [params] = useSearchParams();
  const accountId = params.get('account'); const kind = params.get('type');
  const [account,setAccount]=useState(null);
  useEffect(()=>{if(!supabase||!accountId)return;let live=true;supabase.from('public_account_catalog').select('id,title,game_name').eq('id',accountId).maybeSingle().then(({data})=>{if(live)setAccount(data);});return()=>{live=false;};},[accountId]);
  if(!isConfigured)return <main className="shell page-main"><div className="page-eyebrow">CONTACT THE SELLER</div><SetupEmpty/></main>;
  if(!accountId||!['buy','rent'].includes(kind))return <main className="shell page-main"><div className="empty-panel">Choose an account before checkout. <Link to="/accounts">Browse accounts</Link></div></main>;
  if(!account)return <main className="shell page-main"><div className="empty-panel">This listing is no longer available.</div></main>;
  const text=`Hi @Artz_v2, I want to ${kind} the ${account.game_name} account "${account.title}" (listing ${account.id}).`;
  return <main className="shell page-main narrow-main"><div className="page-eyebrow">ARRANGE YOUR {kind.toUpperCase()}</div><div className="checkout-card"><span className="game-name">{account.game_name} · {kind.toUpperCase()}</span><h1>{account.title}</h1><p>Online checkout is turned off. Message the seller to arrange this {kind} directly.</p>{kind==='rent'&&<Link className="button button-primary pay-button" to={`/rent?account=${account.id}`}>Choose hours and request approval <ArrowRight size={16}/></Link>}<a className="button button-secondary pay-button" href={sellerTelegram(text)} target="_blank" rel="noreferrer">Message @Artz_v2 on Telegram <ArrowRight size={16}/></a></div></main>;
}

function RentalRequest(){
  const [params]=useSearchParams();const navigate=useNavigate();const accountId=params.get('account');
  const [account,setAccount]=useState(null);const [nickname,setNickname]=useState('');const [telegram,setTelegram]=useState('');const [hours,setHours]=useState('1');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{if(!supabase||!accountId)return;let live=true;supabase.from('public_account_catalog').select('id,title,game_name,rent_price').eq('id',accountId).maybeSingle().then(({data})=>{if(live)setAccount(data);});return()=>{live=false;};},[accountId]);
  async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/rental-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create',account_id:accountId,nickname,telegram_username:telegram,duration_hours:Number(hours)})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Could not submit the rental request.');localStorage.setItem(`artzzy-rental-${result.request_id}`,result.token);navigate(`/rent-status/${result.request_id}`);}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  if(!isConfigured)return <main className="shell page-main"><SetupEmpty/></main>;
  if(!accountId)return <main className="shell page-main"><div className="empty-panel">Choose an account before requesting a rental. <Link to="/accounts">Browse accounts</Link></div></main>;
  if(!account)return <main className="shell page-main"><div className="empty-panel">Loading rental listing…</div></main>;
  if(!(Number(account.rent_price)>0))return <main className="shell page-main"><div className="empty-panel">This listing does not have an hourly rental price. <Link to="/accounts">Browse accounts</Link></div></main>;
  return <main className="shell page-main narrow-main"><div className="page-eyebrow">RENTAL REQUEST <span>/</span> OWNER APPROVAL</div><div className="auth-card"><span className="game-name">{account.game_name}</span><h1>{account.title}</h1><p>Choose how many hours you need. Your rental timer starts only if the owner approves.</p><form onSubmit={submit}><label>Nickname<input required maxLength={100} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Name to show with your request"/></label><label>Telegram username (optional)<input maxLength={32} value={telegram} onChange={e=>setTelegram(e.target.value)} placeholder="@yourname"/></label><label>Hours (1–{MAX_RENTAL_HOURS})<input type="number" required min="1" max={MAX_RENTAL_HOURS} step="1" value={hours} onChange={e=>setHours(e.target.value)}/></label><div className="checkout-line"><span>{money(account.rent_price)} × {Number(hours)||0} hour(s)</span><b>{money(rentalQuote(account.rent_price,hours)??0)}</b></div><button className="button button-primary" disabled={busy||!(Number(account.rent_price)>0)}>{busy?'Sending request…':'Send rental request'} <ArrowRight size={16}/></button></form>{message&&<div className="form-message">{message}</div>}<p className="checkout-hint">You can request as a guest. We’ll show a Telegram link so you can message @Artz_v2 while you wait.</p></div></main>;
}

function RentalRequestStatus(){
  const {requestId}=useParams();const [request,setRequest]=useState(null);const [message,setMessage]=useState('Loading request…');const [now,setNow]=useState(Date.now());const [offset,setOffset]=useState(0);
  useEffect(()=>{let live=true;let token='';try{token=localStorage.getItem(`artzzy-rental-${requestId}`)||'';}catch{}if(!token){setMessage('This browser does not have the private link for this request. Start a new request or message the seller.');return;}async function load(){const response=await fetch('/api/rental-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'status',request_id:requestId,token})});const result=await response.json().catch(()=>({}));if(!live)return;if(!response.ok){setMessage(result.error||'Could not load this request.');return;}setRequest(result);setOffset(new Date(result.server_now).getTime()-Date.now());setMessage('');}load();const poll=setInterval(load,10000);return()=>{live=false;clearInterval(poll);};},[requestId]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const expires=request?.expires_at?new Date(request.expires_at).getTime():0;const secondsLeft=Math.max(0,Math.floor((expires-(now+offset))/1000));const timerText=`${Math.floor(secondsLeft/3600)}h ${String(Math.floor(secondsLeft%3600/60)).padStart(2,'0')}m ${String(secondsLeft%60).padStart(2,'0')}s`;
  const telegramMessage=request?`Hi @Artz_v2, my rental request ${request.id} for ${request.game_name} / ${request.account_title} is ${request.status}.`: 'Hi @Artz_v2, I have a question about renting an account.';
  return <main className="shell page-main narrow-main"><div className="page-eyebrow">RENTAL REQUEST STATUS</div><div className="checkout-card"><h1>{request?.account_title||'Your request'}</h1>{message?<p>{message}</p>:<><p>Request ID: {request.id}</p>{request.status==='pending'?<><strong>Waiting for owner approval</strong><p>Your {request.duration_hours}-hour timer has not started. This page checks for updates automatically.</p></>:request.status==='approved'&&secondsLeft>0?<><strong>Approved · rental is active</strong><p>Time remaining: <b>{timerText}</b></p><p>Starts {new Date(request.started_at).toLocaleString()} · ends {new Date(request.expires_at).toLocaleString()}</p></>:request.status==='approved'?<><strong>Rental time ended</strong><p>The requested {request.duration_hours} hours have passed.</p></>:request.status==='rejected'?<><strong>Request not approved</strong><p>The owner could not accept this rental request.</p></>:<strong>Request status: {request.status}</strong>}<div className="checkout-line"><span>{request.duration_hours} hour(s)</span><b>{money(request.total_price)}</b></div></>}<a className="button button-secondary pay-button" href={sellerTelegram(telegramMessage)} target="_blank" rel="noreferrer">Message @Artz_v2 on Telegram <ArrowRight size={16}/></a></div></main>;
}

function PaymentResult(){const [params]=useSearchParams();const [row,setRow]=useState(null);const [message,setMessage]=useState('Checking order status…');useEffect(()=>{if(!supabase)return;let live=true;supabase.rpc('get_my_orders').then(({data,error})=>{if(!live)return;const found=(data||[]).find(o=>o.order_id===params.get('order'));setRow(found||null);setMessage(error?'Sign in to check this order.':found?`Current status: ${found.order_status}. The provider callback is the source of truth.`:'We have not received confirmation yet. This page does not confirm payment by itself.');});return()=>{live=false;};},[params]);return <main className="shell page-main narrow-main"><div className="page-eyebrow">PAYMENT UPDATE</div><div className="empty-panel large-empty"><div className="empty-icon"><ShieldCheck/></div><div><strong>{row?.order_status==='paid'?'Payment confirmed':row?.order_status==='refund_required'?'Payment needs review':'Waiting for payment confirmation'}</strong><p>{message}</p></div><button className="button button-secondary" onClick={()=>location.reload()}>Refresh status</button></div></main>}

function Login(){ const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const navigate=useNavigate(); const [params]=useSearchParams(); async function signIn(e){e.preventDefault();if(!supabase){setMessage('Connect the new Supabase project before signing in.');return;}setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setMessage(error.message);else{const next=params.get('next');navigate(next&&next.startsWith('/')?next:'/admin');}} async function forgotPassword(){if(!supabase){setMessage('Connect the new Supabase project before resetting your password.');return;}if(!email.trim()){setMessage('Enter your email address above first.');return;}setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/reset-password`});setBusy(false);setMessage(error?.message||'If an account exists for that email, a password reset link is on its way.');}
 return <main className="shell page-main narrow-main"><div className="page-eyebrow">YOUR PLAYER ACCOUNT</div><div className="auth-card"><span className="auth-mark"><CircleUserRound/></span><h1>Good to have you.</h1><p>Sign in to check orders, access your accounts and track rentals.</p><form onSubmit={signIn}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<div className="password-field"><input type={showPassword?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/><button type="button" className="password-toggle" aria-label={showPassword?'Hide password':'Show password'} aria-pressed={showPassword} onClick={()=>setShowPassword(!showPassword)}>{showPassword?'Hide':'Show'}</button></div></label><button type="button" className="forgot-password" onClick={forgotPassword} disabled={busy}>Forgot password?</button><button className="button button-primary" disabled={busy}>{busy?'Signing in…':'Sign in'} <ArrowRight size={16}/></button></form>{message&&<div className="form-message">{message}</div>}<div className="auth-foot">New around here? <button onClick={async()=>{if(!supabase){setMessage('Connect the new Supabase project before registering.');return;} const {error}=await supabase.auth.signUp({email,password});setMessage(error?.message||'Check your email to confirm your account.');}}>Create an account</button></div></div></main>;
}

function ResetPassword(){const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function savePassword(e){e.preventDefault();if(!supabase){setMessage('Password reset is unavailable until Supabase is connected.');return;}setBusy(true);const {error}=await supabase.auth.updateUser({password});setBusy(false);setMessage(error?.message||'Your password has been changed. You can now sign in with it.');if(!error)setPassword('');}return <main className="shell page-main narrow-main"><div className="page-eyebrow">YOUR PLAYER ACCOUNT</div><div className="auth-card"><span className="auth-mark"><CircleUserRound/></span><h1>Choose a new password.</h1><p>Enter a new password for your account.</p><form onSubmit={savePassword}><label>New password<div className="password-field"><input type={showPassword?'text':'password'} required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/><button type="button" className="password-toggle" onClick={()=>setShowPassword(!showPassword)}>{showPassword?'Hide':'Show'}</button></div></label><button className="button button-primary" disabled={busy}>{busy?'Saving…':'Save new password'} <ArrowRight size={16}/></button></form>{message&&<div className="form-message">{message}</div>}</div></main>}

function Profile(){const [session,setSession]=useState(null);const [name,setName]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){const {data:profile}=await supabase.from('profiles').select('display_name').eq('id',data.session.user.id).maybeSingle();setName(profile?.display_name||'');}});},[]);async function save(e){e.preventDefault();if(!session)return;setBusy(true);const {error}=await supabase.from('profiles').update({display_name:name.trim()}).eq('id',session.user.id);setBusy(false);setMessage(error?.message||'Profile saved.');}return <main className="shell page-main narrow-main"><div className="page-eyebrow">PLAYER ACCOUNT</div>{!session?<div className="empty-panel"><div><strong>Sign in to view your profile.</strong></div><Link className="button button-primary" to="/login">Sign in</Link></div>:<div className="auth-card"><span className="auth-mark"><CircleUserRound/></span><h1>Your profile.</h1><p>{session.user.email}</p><form onSubmit={save}><label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><button className="button button-primary" disabled={busy}>{busy?'Saving…':'Save profile'} <ArrowRight size={16}/></button></form>{message&&<div className="form-message">{message}</div>}</div>}</main>}

function Orders(){return <CustomerActivity mode="orders"/>}
function Rentals(){return <CustomerActivity mode="rentals"/>}
function CustomerActivity({mode}){const [session,setSession]=useState(null);const [rows,setRows]=useState([]);const [offset,setOffset]=useState(0);const [now,setNow]=useState(Date.now());const [message,setMessage]=useState('');const isRentals=mode==='rentals';
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!session||!supabase)return;supabase.rpc('get_my_orders').then(({data})=>{const all=data||[];setRows(isRentals?all.filter(r=>r.kind==='rent'):all);if(all[0]?.server_now)setOffset(new Date(all[0].server_now).getTime()-Date.now());});},[session,isRentals]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const formatRemaining=(expires)=>{const sec=Math.max(0,Math.floor((new Date(expires).getTime()-(now+offset))/1000));const d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600),m=Math.floor(sec%3600/60),s=sec%60;return `${String(d).padStart(2,'0')}d ${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`;};
 return <main className="shell page-main"><div className="page-eyebrow">PLAYER DASHBOARD</div><div className="dashboard-head"><span>{isRentals?<Gamepad2/>:<ShoppingBag/>}</span><div><h1>{isRentals?'Your rentals':'Your orders'}</h1><p>{isRentals?'Track active rentals with a server-timed expiry.':'Purchases, order history and seller contact.'}</p></div></div>{!isConfigured?<SetupEmpty/>:!session?<div className="empty-panel"><div><strong>Sign in to see your account activity.</strong><p>Your purchases and rental timers are private to your account.</p></div><Link className="button button-primary" to="/login">Sign in <ArrowRight size={15}/></Link></div>:rows.length===0?<div className="empty-panel"><div><strong>{isRentals?'No rentals yet.':'No orders yet.'}</strong><p>New purchases and rental requests are arranged directly with the seller.</p></div><Link to="/accounts" className="text-link">Browse accounts <ArrowRight size={15}/></Link></div>:<div className="activity-list">{rows.map(r=><article className="activity-card" key={r.order_id}><div className="activity-card-head"><div><span className="game-name">{r.game_name} · {r.kind}</span><h3>{r.account_title}</h3></div><span className={`order-state state-${r.order_status}`}>{r.order_status.replace('_',' ')}</span></div><div className="activity-meta"><span>{money(r.amount)}</span><span>Order {r.order_id.slice(0,8).toUpperCase()}</span><span>{new Date(r.created_at).toLocaleDateString()}</span></div>{r.rental_expires_at&&<div className="rental-timer"><small>{r.rental_status==='active'&&new Date(r.rental_expires_at).getTime()>now+offset?'TIME REMAINING':'RENTAL STATUS'}</small><b>{r.rental_status==='active'&&new Date(r.rental_expires_at).getTime()>now+offset?formatRemaining(r.rental_expires_at):r.rental_status?.toUpperCase()}</b><span>Expires {new Date(r.rental_expires_at).toLocaleString()}</span></div>}<a className="credential-button" href={sellerTelegram(`Hi @Artz_v2, I am contacting you about my ${r.game_name} ${r.kind} order ${r.order_id}.`)} target="_blank" rel="noreferrer">Contact seller on Telegram <ArrowRight size={14}/></a></article>)}</div>}{message&&<div className="form-message">{message}</div>}</main>}

function Games(){return <main className="shell page-main"><div className="page-eyebrow">CHOOSE YOUR GAME</div><div className="page-title-row"><div><h1>Play your <span>way.</span></h1><p>Browse available accounts by game.</p></div></div><GameList/></main>}
function Admin(){
  const [session,setSession]=useState(null);const [tab,setTab]=useState('accounts');const [data,setData]=useState({games:[],accounts:[],plans:[],orders:[],payments:[],rentals:[],rental_requests:[],customers:[]});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const blank={id:'',game_id:'',title:'',description:'',features:'',cover_image_url:'',buy_price:'',rent_hourly_price:'',status:'available'};const [account,setAccount]=useState(blank);const [game,setGame]=useState({id:'',name:'',slug:'',description:'',cover_image_url:''});
  useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
  async function callApi(action,payload={}){if(!session)return;const response=await fetch('/api/admin-marketplace',{method:action?'POST':'GET',headers:{authorization:`Bearer ${session.access_token}`,...(action?{'content-type':'application/json'}:{})},body:action?JSON.stringify({action,data:payload}):undefined});const result=await response.json().catch(()=>null);if(!result||typeof result!=='object')throw new Error('The admin server function did not respond. Use your deployed Netlify site, or run the project with Netlify Dev. On Netlify, check that VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.');if(!response.ok)throw new Error(result.error||'Admin request failed.');if(!action&&(!Array.isArray(result.games)||!Array.isArray(result.accounts)))throw new Error('The admin server function returned incomplete data. Check its Netlify function logs.');if(action&&result.error)throw new Error(result.error);return result;}
  async function reload(){try{setError('');setData(await callApi());}catch(e){setError(e.message);}}
  useEffect(()=>{if(session)reload();},[session]);
  useEffect(()=>{if(!session)return;const timer=setInterval(()=>{callApi().then(setData).catch(e=>setError(e.message));},15000);return()=>clearInterval(timer);},[session]);
  async function action(name,payload){try{setBusy(true);await callApi(name,payload);await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function saveAccount(e){e.preventDefault();await action('save-account',account);setAccount(blank);}
  async function saveGame(e){e.preventDefault();await action('save-game',{...game,slug:game.id?game.slug:nextGameSlug(game.name,data.games)});setGame({id:'',name:'',slug:'',description:'',cover_image_url:''});}
  if(!isConfigured)return <main className="shell page-main"><div className="page-eyebrow">STORE MANAGEMENT</div><SetupEmpty/></main>;
  if(!session)return <main className="shell page-main"><div className="page-eyebrow">STORE MANAGEMENT</div><div className="empty-panel"><div><strong>Administrator sign in required.</strong><p>Only a profile promoted to admin in the dedicated database can access this console.</p></div><Link className="button button-primary" to="/login">Sign in <ArrowRight size={15}/></Link></div></main>;
  const accountName=(id)=>data.accounts.find(a=>a.id===id)?.title||id?.slice(0,8);const customerName=(id)=>data.customers.find(c=>c.id===id)?.email||id?.slice(0,8);const pendingRequestCount=data.rental_requests.filter(r=>r.status==='pending').length;const tabs=[['accounts','Accounts'],['games','Games'],['rental_requests',`Rental requests${pendingRequestCount?` (${pendingRequestCount})`:''}`],['orders','Orders'],['rentals','Rentals'],['customers','Customers']];
  return <main className="shell page-main"><div className="page-eyebrow">STORE MANAGEMENT</div><div className="page-title-row"><div><h1>Admin <span>console.</span></h1><p>Manage this store’s independent inventory, customers and orders.</p></div><button className="button button-secondary" onClick={reload}>Refresh</button></div>{error&&<div className="admin-error">{error}</div>}<div className="admin-tabs">{tabs.map(([key,label])=><button className={tab===key?'selected':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</div>
  {tab==='accounts'&&<><form className="admin-form" onSubmit={saveAccount}><h2>{account.id?'Edit account':'Add account'}</h2><div className="admin-form-grid"><label>Game<select required value={account.game_id} onChange={e=>setAccount({...account,game_id:e.target.value})}><option value="">Select game</option>{data.games.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label><label>Listing title<input required value={account.title} onChange={e=>setAccount({...account,title:e.target.value})}/></label><label>Buy price (RM, optional)<input type="number" step="0.01" min="0" value={account.buy_price} onChange={e=>setAccount({...account,buy_price:e.target.value})}/></label><label>Rent price per hour (RM, optional)<input type="number" step="0.01" min="0.01" value={account.rent_hourly_price} onChange={e=>setAccount({...account,rent_hourly_price:e.target.value})}/></label><label>Inventory status<select value={account.status} onChange={e=>setAccount({...account,status:e.target.value})}><option value="available">Available</option><option value="disabled">Disabled</option></select></label><label className="span-two">Description<textarea rows="3" value={account.description} onChange={e=>setAccount({...account,description:e.target.value})}/></label><label>Features (comma separated)<input value={account.features} onChange={e=>setAccount({...account,features:e.target.value})}/></label><label>Cover image URL<input value={account.cover_image_url} onChange={e=>setAccount({...account,cover_image_url:e.target.value})}/><ImageUpload onUploaded={url=>setAccount({...account,cover_image_url:url})}/></label><div className="span-two"><small>No account login details are stored here. Customers contact you to arrange access.</small></div></div><div className="admin-form-actions"><button className="button button-primary" disabled={busy}>{account.id?'Save account':'Add account'} <ArrowRight size={15}/></button>{account.id&&<button type="button" className="button button-secondary" onClick={()=>setAccount(blank)}>Cancel edit</button>}</div></form><div className="admin-table-wrap"><h2>Inventory <span>{data.accounts.length}</span></h2><table><thead><tr><th>Account</th><th>Game</th><th>Buy</th><th>Rent / hour</th><th>Status</th><th></th></tr></thead><tbody>{data.accounts.map(a=><tr key={a.id}><td>{a.title}</td><td>{data.games.find(g=>g.id===a.game_id)?.name||'—'}</td><td>{money(a.buy_price)}</td><td>{money(a.rent_hourly_price)}</td><td>{a.status}</td><td className="table-actions"><button onClick={()=>setAccount({...a,features:(a.features||[]).join(', ')})}>Edit</button><button onClick={()=>action('set-account-status',{id:a.id,status:a.status==='disabled'?'available':'disabled'})}>{a.status==='disabled'?'Enable':'Disable'}</button><button onClick={()=>{if(window.confirm(`Delete ${a.title}?`))action('delete-account',{id:a.id});}}>Delete</button></td></tr>)}</tbody></table></div></>}
  {tab==='games'&&<><form className="admin-form" onSubmit={saveGame}><h2>{game.id?'Edit game':'Add game'}</h2><div className="admin-form-grid"><label>Game name<input required value={game.name} onChange={e=>setGame({...game,name:e.target.value,slug:game.id?game.slug:nextGameSlug(e.target.value,data.games)})}/></label><label>Slug<input required readOnly value={game.id?game.slug:nextGameSlug(game.name,data.games)}/><small>Generated automatically. PUBG uses Pubg; eFootball uses Pes.</small></label><label className="span-two">Description<input value={game.description} onChange={e=>setGame({...game,description:e.target.value})}/></label><label className="span-two">Cover image URL<input value={game.cover_image_url} onChange={e=>setGame({...game,cover_image_url:e.target.value})}/><ImageUpload onUploaded={url=>setGame({...game,cover_image_url:url})}/></label></div><div className="admin-form-actions"><button className="button button-primary" disabled={busy}>{game.id?'Save game':'Add game'}</button></div></form><div className="admin-table-wrap"><h2>Games</h2><table><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th></th></tr></thead><tbody>{data.games.map(g=><tr key={g.id}><td>{g.name}</td><td>{g.slug}</td><td>{g.is_active?'Active':'Hidden'}</td><td className="table-actions"><button onClick={()=>setGame(g)}>Edit</button><button onClick={()=>{if(window.confirm(`Delete ${g.name}?`))action('delete-game',{id:g.id});}}>Delete</button></td></tr>)}</tbody></table></div></>}
  {tab==='rental_requests'&&<div className="admin-table-wrap"><h2>Guest rental requests <span>{pendingRequestCount} waiting</span></h2><p>New requests refresh automatically while this page is open. Approving starts the server-timed countdown.</p><table><thead><tr><th>Listing</th><th>Nickname</th><th>Telegram</th><th>Hours</th><th>Total</th><th>Status</th><th>Requested</th><th>Decision</th></tr></thead><tbody>{data.rental_requests.map(r=>{const expired=r.status==='approved'&&r.expires_at&&new Date(r.expires_at).getTime()<=Date.now();return <tr key={r.id}><td>{r.game_name} · {r.account_title}<small>{r.id.slice(0,8)}</small></td><td>{r.customer_name}</td><td>{r.customer_telegram?<a href={`https://t.me/${r.customer_telegram.replace(/^@/,'')}`} target="_blank" rel="noreferrer">{r.customer_telegram}</a>:'—'}</td><td>{r.duration_hours}h × {money(r.hourly_rate)}</td><td>{money(r.total_price)}</td><td>{expired?'expired':r.status}{r.status==='approved'&&r.expires_at&&!expired&&<small>Until {new Date(r.expires_at).toLocaleString()}</small>}</td><td>{new Date(r.created_at).toLocaleString()}</td><td className="table-actions">{r.status==='pending'?<><button disabled={busy} onClick={()=>action('approve-rental-request',{id:r.id})}>Approve & start</button><button disabled={busy} onClick={()=>action('reject-rental-request',{id:r.id})}>Decline</button></>:'—'}</td></tr>;})}</tbody></table></div>}
  {tab==='orders'&&<div className="admin-table-wrap"><h2>Orders <span>Latest 100</span></h2><table><thead><tr><th>Order</th><th>Customer</th><th>Account</th><th>Type</th><th>Amount</th><th>Payment status</th><th>Order status</th><th>Date</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.id.slice(0,8)}</td><td>{customerName(o.customer_id)}</td><td>{accountName(o.account_id)}</td><td>{o.kind}</td><td>{money(o.amount)}</td><td>{data.payments.find(p=>p.order_id===o.id)?.status||'—'}</td><td>{o.status}</td><td>{new Date(o.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
  {tab==='rentals'&&<div className="admin-table-wrap"><h2>Rentals <span>Latest 100</span></h2><table><thead><tr><th>Account</th><th>Customer</th><th>Status</th><th>Start</th><th>Expires</th><th>Manage</th></tr></thead><tbody>{data.rentals.map(r=><tr key={r.id}><td>{accountName(r.account_id)}</td><td>{customerName(r.customer_id)}</td><td>{new Date(r.expires_at).getTime()<Date.now()&&r.status==='active'?'expired':r.status}</td><td>{new Date(r.started_at).toLocaleString()}</td><td>{new Date(r.expires_at).toLocaleString()}</td><td className="table-actions"><button onClick={()=>{const days=Number(window.prompt('Extend by how many days?','7'));if(days)action('extend-rental',{id:r.id,days});}}>Extend</button><button onClick={()=>{if(window.confirm('End this rental now?'))action('end-rental',{id:r.id});}}>End</button></td></tr>)}</tbody></table></div>}
  {tab==='customers'&&<div className="admin-table-wrap"><h2>Customers <span>Latest 100</span></h2><table><thead><tr><th>Email</th><th>Name</th><th>Joined</th><th>Orders</th></tr></thead><tbody>{data.customers.map(c=><tr key={c.id}><td>{c.email}</td><td>{c.display_name||'—'}</td><td>{new Date(c.created_at).toLocaleDateString()}</td><td>{data.orders.filter(o=>o.customer_id===c.id).length}</td></tr>)}</tbody></table></div>}
  </main>
}

function ImageUpload({onUploaded}){const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function upload(file){if(!file)return;if(file.size>5*1024*1024){setMessage('Maximum image size is 5 MB.');return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('Use JPG, PNG or WebP.');return;}setBusy(true);const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('store-media').upload(path,file,{contentType:file.type});if(error)setMessage(error.message);else{onUploaded(supabase.storage.from('store-media').getPublicUrl(path).data.publicUrl);setMessage('Image uploaded.');}setBusy(false);}
return <div className="upload-control"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])} disabled={busy}/><small>{busy?'Uploading…':message||'Upload JPG, PNG or WebP (5 MB max)'}</small></div>}
function SetupLink(){return <a href="#setup" className="text-link">Setup guide <ArrowRight size={15}/></a>}
function SetupEmpty(){return <div className="empty-panel large-empty"><div className="empty-icon"><Sparkles/></div><div><strong>Connect your new store to get started.</strong><p>This independent marketplace is ready for its own game list and stock. No accounts are imported from any other system.</p></div><SetupLink/></div>}
function SetupFooter(){return <footer className="footer" id="setup"><div className="shell footer-inner"><Link to="/" className="brand"><span className="brand-mark"><Gamepad2 size={18}/></span><span>ARTZZY<span className="brand-light"> STORE</span></span></Link><div className="footer-right"><a href="https://t.me/Artz_v2" target="_blank" rel="noreferrer">Contact on Telegram: @Artz_v2</a><span className="footer-divider"/><span>© 2026 ARTZZY STORE</span><span className="footer-divider"/><span>Independent player marketplace</span></div></div></footer>}

function App(){return <><StatusStrip/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/games" element={<Games/>}/><Route path="/accounts" element={<Accounts/>}/><Route path="/accounts/:id" element={<AccountDetail/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/rent" element={<RentalRequest/>}/><Route path="/rent-status/:requestId" element={<RentalRequestStatus/>}/><Route path="/login" element={<Login/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/profile" element={<Profile/>}/><Route path="/orders" element={<Orders/>}/><Route path="/rentals" element={<Rentals/>}/><Route path="/payment-result" element={<PaymentResult/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<main className="shell page-main"><div className="empty-panel">That page isn't here yet. <Link to="/">Go home</Link></div></main>}/></Routes></>}

export default App;
